/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RKoQMg5IJuE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center justify-between px-4 py-2 border-b">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">Acme Inc</span>
        </Link>
        <nav className="hidden lg:flex gap-6">
          <Link className="text-sm hover:underline" href="#">
            Home
          </Link>
          <Link className="text-sm hover:underline" href="#">
            Shop
          </Link>
          <Link className="text-sm hover:underline" href="#">
            About
          </Link>
          <Link className="text-sm hover:underline" href="#">
            Contact
          </Link>
        </nav>
        <form className="flex items-center gap-2">
          <Input className="w-64" placeholder="Search products..." type="search" />
          <Button variant="outline">
            <SearchIcon className="h-4 w-4" />
            <span className="sr-only">Search</span>
          </Button>
        </form>
      </header>
      <main className="flex flex-col lg:flex-row gap-4 lg:gap-6 p-4 md:p-6">
        <aside className="w-full lg:w-64">
          <h2 className="text-lg font-semibold mb-2">Filters</h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-medium">Categories</h3>
              <div className="space-y-1 mt-2">
                <Checkbox id="clothing">Clothing</Checkbox>
                <Checkbox id="electronics">Electronics</Checkbox>
                <Checkbox id="home">Home</Checkbox>
                <Checkbox id="beauty">Beauty</Checkbox>
              </div>
            </div>
            <div>
              <h3 className="font-medium">Price Range</h3>
              <div className="space-y-1 mt-2">
                <Checkbox id="under-25">$25 and under</Checkbox>
                <Checkbox id="25-50">$25 - $50</Checkbox>
                <Checkbox id="50-100">$50 - $100</Checkbox>
                <Checkbox id="100-200">$100 - $200</Checkbox>
                <Checkbox id="200-plus">$200 and above</Checkbox>
              </div>
            </div>
            <div>
              <h3 className="font-medium">Sort By</h3>
              <div className="space-y-1 mt-2">
                <RadioGroup defaultValue="featured">
                  <Label className="flex items-center gap-2 font-normal" htmlFor="featured">
                    <RadioGroupItem id="featured" value="featured" />
                    Featured
                  </Label>
                  <Label className="flex items-center gap-2 font-normal" htmlFor="low-to-high">
                    <RadioGroupItem id="low-to-high" value="low-to-high" />
                    Price: Low to High
                  </Label>
                  <Label className="flex items-center gap-2 font-normal" htmlFor="high-to-low">
                    <RadioGroupItem id="high-to-low" value="high-to-low" />
                    Price: High to Low
                  </Label>
                </RadioGroup>
              </div>
            </div>
          </div>
        </aside>
        <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6">
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 1</h3>
              <p className="text-gray-500">$99.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 2</h3>
              <p className="text-gray-500">$79.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 3</h3>
              <p className="text-gray-500">$59.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 4</h3>
              <p className="text-gray-500">$49.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 5</h3>
              <p className="text-gray-500">$39.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
          <div className="border rounded-lg overflow-hidden">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Product 6</h3>
              <p className="text-gray-500">$29.99</p>
              <Button className="mt-2">Add to Cart</Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
